Script started on Tue 11 Nov 2014 08:21:38 PM PST
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ #testing ls in u[Kcurrent dir with and wi thout flags
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls
[34mbin[0m  [32mbin_link[0m  LICENSE[0m  Makefile[0m  README.md[0m  [34msrc[0m  [34mtests[0m  
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls -l
total 24
drwxrwxr-x 2 alexander alexander 4096 Nov 11 20:21 [34mbin[0m
lrwxrwxrwx 1 alexander alexander 3 Nov 11 19:38 [32mbin_link[0m
-rw-rw-r-- 1 alexander alexander 1486 Nov 11 19:19 LICENSE
-rw-rw-r-- 1 alexander alexander 573 Nov 11 19:27 Makefile
-rw-rw-r-- 1 alexander alexander 2854 Nov 11 19:27 README.md
drwxrwxr-x 2 alexander alexander 4096 Nov 11 20:19 [34msrc[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 11 20:21 [34mtests[0m
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls -a
[34;100m.[0m  [34;100m..[0m  [34mbin[0m  [32mbin_link[0m  [34;100m.git[0m  [100m.hidden[0m[0m  LICENSE[0m  Makefile[0m  README.md[0m  [34msrc[0m  [34mtests[0m  
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls -l[KR
.:
[34mbin[0m  [32mbin_link[0m  LICENSE[0m  Makefile[0m  README.md[0m  [34msrc[0m  [34mtests[0m  

./bin:
[32mcp[0m  [32mls[0m  [32mrshell[0m  

./src:
cp.cpp[0m  hw0.cpp[0m  ls.cpp[0m  Timer.h[0m  

./tests:
exec.script[0m  ls.script[0m  
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ #testing ls whn[Ken passing in [Kv[K various co mbinations of flags
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls -a -l
total 36
drwxrwxr-x 6 alexander alexander 4096 Nov 11 19:44 [34;100m.[0m
drwxrwxr-x 5 alexander alexander 4096 Nov 11 19:19 [34;100m..[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 11 20:21 [34mbin[0m
lrwxrwxrwx 1 alexander alexander 3 Nov 11 19:38 [32mbin_link[0m
drwxrwxr-x 8 alexander alexander 4096 Nov 11 20:20 [34;100m.git[0m
-rw-rw-r-- 1 alexander alexander 0 Nov 11 19:44 [100m.hidden[0m
-rw-rw-r-- 1 alexander alexander 1486 Nov 11 19:19 LICENSE
-rw-rw-r-- 1 alexander alexander 573 Nov 11 19:27 Makefile
-rw-rw-r-- 1 alexander alexander 2854 Nov 11 19:27 README.md
drwxrwxr-x 2 alexander alexander 4096 Nov 11 20:19 [34msrc[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 11 20:21 [34mtests[0m
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls -la
total 36
drwxrwxr-x 6 alexander alexander 4096 Nov 11 19:44 [34;100m.[0m
drwxrwxr-x 5 alexander alexander 4096 Nov 11 19:19 [34;100m..[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 11 20:21 [34mbin[0m
lrwxrwxrwx 1 alexander alexander 3 Nov 11 19:38 [32mbin_link[0m
drwxrwxr-x 8 alexander alexander 4096 Nov 11 20:20 [34;100m.git[0m
-rw-rw-r-- 1 alexander alexander 0 Nov 11 19:44 [100m.hidden[0m
-rw-rw-r-- 1 alexander alexander 1486 Nov 11 19:19 LICENSE
-rw-rw-r-- 1 alexander alexander 573 Nov 11 19:27 Makefile
-rw-rw-r-- 1 alexander alexander 2854 Nov 11 19:27 README.md
drwxrwxr-x 2 alexander alexander 4096 Nov 11 20:19 [34msrc[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 11 20:21 [34mtests[0m
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls -Rl
.:
total 24
drwxrwxr-x 2 alexander alexander 4096 Nov 11 20:21 [34mbin[0m
lrwxrwxrwx 1 alexander alexander 3 Nov 11 19:38 [32mbin_link[0m
-rw-rw-r-- 1 alexander alexander 1486 Nov 11 19:19 LICENSE
-rw-rw-r-- 1 alexander alexander 573 Nov 11 19:27 Makefile
-rw-rw-r-- 1 alexander alexander 2854 Nov 11 19:27 README.md
drwxrwxr-x 2 alexander alexander 4096 Nov 11 20:19 [34msrc[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 11 20:21 [34mtests[0m

./bin:
total 216
-rwxrwxr-x 1 alexander alexander 24435 Nov 11 20:21 [32mcp[0m
-rwxrwxr-x 1 alexander alexander 158823 Nov 11 20:21 [32mls[0m
-rwxrwxr-x 1 alexander alexander 33183 Nov 11 20:21 [32mrshell[0m

./src:
total 44
-rw-rw-r-- 1 alexander alexander 5903 Nov 11 19:19 cp.cpp
-rw-rw-r-- 1 alexander alexander 10341 Nov 11 19:19 hw0.cpp
-rw-rw-r-- 1 alexander alexander 18768 Nov 11 20:19 ls.cpp
-rw-rw-r-- 1 alexander alexander 4025 Nov 11 19:19 Timer.h

./tests:
total 20
-rw-rw-r-- 1 alexander alexander 15164 Nov 11 19:19 exec.script
-rw-rw-r-- 1 alexander alexander 4096 Nov 11 20:22 ls.script
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls -l -R
.:
total 24
drwxrwxr-x 2 alexander alexander 4096 Nov 11 20:21 [34mbin[0m
lrwxrwxrwx 1 alexander alexander 3 Nov 11 19:38 [32mbin_link[0m
-rw-rw-r-- 1 alexander alexander 1486 Nov 11 19:19 LICENSE
-rw-rw-r-- 1 alexander alexander 573 Nov 11 19:27 Makefile
-rw-rw-r-- 1 alexander alexander 2854 Nov 11 19:27 README.md
drwxrwxr-x 2 alexander alexander 4096 Nov 11 20:19 [34msrc[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 11 20:21 [34mtests[0m

./bin:
total 216
-rwxrwxr-x 1 alexander alexander 24435 Nov 11 20:21 [32mcp[0m
-rwxrwxr-x 1 alexander alexander 158823 Nov 11 20:21 [32mls[0m
-rwxrwxr-x 1 alexander alexander 33183 Nov 11 20:21 [32mrshell[0m

./src:
total 44
-rw-rw-r-- 1 alexander alexander 5903 Nov 11 19:19 cp.cpp
-rw-rw-r-- 1 alexander alexander 10341 Nov 11 19:19 hw0.cpp
-rw-rw-r-- 1 alexander alexander 18768 Nov 11 20:19 ls.cpp
-rw-rw-r-- 1 alexander alexander 4025 Nov 11 19:19 Timer.h

./tests:
total 20
-rw-rw-r-- 1 alexander alexander 15164 Nov 11 19:19 exec.script
-rw-rw-r-- 1 alexander alexander 4096 Nov 11 20:22 ls.script
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ #testing ls wjem [K[K[K[Khen passing in multiple f lags of same type
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls -l -l -l -l a[K-a
total 36
drwxrwxr-x 6 alexander alexander 4096 Nov 11 19:44 [34;100m.[0m
drwxrwxr-x 5 alexander alexander 4096 Nov 11 19:19 [34;100m..[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 11 20:21 [34mbin[0m
lrwxrwxrwx 1 alexander alexander 3 Nov 11 19:38 [32mbin_link[0m
drwxrwxr-x 8 alexander alexander 4096 Nov 11 20:20 [34;100m.git[0m
-rw-rw-r-- 1 alexander alexander 0 Nov 11 19:44 [100m.hidden[0m
-rw-rw-r-- 1 alexander alexander 1486 Nov 11 19:19 LICENSE
-rw-rw-r-- 1 alexander alexander 573 Nov 11 19:27 Makefile
-rw-rw-r-- 1 alexander alexander 2854 Nov 11 19:27 README.md
drwxrwxr-x 2 alexander alexander 4096 Nov 11 20:19 [34msrc[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 11 20:21 [34mtests[0m
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls -a -a -a -a -l
total 36
drwxrwxr-x 6 alexander alexander 4096 Nov 11 19:44 [34;100m.[0m
drwxrwxr-x 5 alexander alexander 4096 Nov 11 19:19 [34;100m..[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 11 20:21 [34mbin[0m
lrwxrwxrwx 1 alexander alexander 3 Nov 11 19:38 [32mbin_link[0m
drwxrwxr-x 8 alexander alexander 4096 Nov 11 20:20 [34;100m.git[0m
-rw-rw-r-- 1 alexander alexander 0 Nov 11 19:44 [100m.hidden[0m
-rw-rw-r-- 1 alexander alexander 1486 Nov 11 19:19 LICENSE
-rw-rw-r-- 1 alexander alexander 573 Nov 11 19:27 Makefile
-rw-rw-r-- 1 alexander alexander 2854 Nov 11 19:27 README.md
drwxrwxr-x 2 alexander alexander 4096 Nov 11 20:19 [34msrc[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 11 20:21 [34mtests[0m
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls -lllllllllllaaaaaaaaaa
total 36
drwxrwxr-x 6 alexander alexander 4096 Nov 11 19:44 [34;100m.[0m
drwxrwxr-x 5 alexander alexander 4096 Nov 11 19:19 [34;100m..[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 11 20:21 [34mbin[0m
lrwxrwxrwx 1 alexander alexander 3 Nov 11 19:38 [32mbin_link[0m
drwxrwxr-x 8 alexander alexander 4096 Nov 11 20:20 [34;100m.git[0m
-rw-rw-r-- 1 alexander alexander 0 Nov 11 19:44 [100m.hidden[0m
-rw-rw-r-- 1 alexander alexander 1486 Nov 11 19:19 LICENSE
-rw-rw-r-- 1 alexander alexander 573 Nov 11 19:27 Makefile
-rw-rw-r-- 1 alexander alexander 2854 Nov 11 19:27 README.md
drwxrwxr-x 2 alexander alexander 4096 Nov 11 20:19 [34msrc[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 11 20:21 [34mtests[0m
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ #testing ls when a[Kpassing in file/dir t hat is in the same dir as ls
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls src
cp.cpp[0m  hw0.cpp[0m  ls.cpp[0m  Timer.h[0m  
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls ./src
cp.cpp[0m  hw0.cpp[0m  ls.cpp[0m  Timer.h[0m  
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls ./src/
cp.cpp[0m  hw0.cpp[0m  ls.cpp[0m  Timer.h[0m  
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/s[Kls src/
cp.cpp[0m  hw0.cpp[0m  ls.cpp[0m  Timer.h[0m  
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls tests src
src:
cp.cpp[0m  hw0.cpp[0m  ls.cpp[0m  Timer.h[0m  

tests:
exec.script[0m  ls.script[0m  
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls src -a test [Ks -l
src:
total 52
drwxrwxr-x 2 alexander alexander 4096 Nov 11 20:19 [34;100m.[0m
drwxrwxr-x 6 alexander alexander 4096 Nov 11 19:44 [34;100m..[0m
-rw-rw-r-- 1 alexander alexander 5903 Nov 11 19:19 cp.cpp
-rw-rw-r-- 1 alexander alexander 10341 Nov 11 19:19 hw0.cpp
-rw-rw-r-- 1 alexander alexander 18768 Nov 11 20:19 ls.cpp
-rw-rw-r-- 1 alexander alexander 4025 Nov 11 19:19 Timer.h

tests:
total 32
drwxrwxr-x 2 alexander alexander 4096 Nov 11 20:21 [34;100m.[0m
drwxrwxr-x 6 alexander alexander 4096 Nov 11 19:44 [34;100m..[0m
-rw-rw-r-- 1 alexander alexander 15164 Nov 11 19:19 exec.script
-rw-rw-r-- 1 alexander alexander 8192 Nov 11 20:23 ls.script
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls Makefile
Makefile 
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin ./[K[K[K/ls ./Makefile
./Makefile 
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls README.md Mae[Kkefile
Makefile README.md 
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls Makeil[K[Kfie[Kle -l LICENSE
-rw-rw-r-- 1 alexander alexander 1486 Nov 11 19:19 LICENSE
-rw-rw-r-- 1 alexander alexander 573 Nov 11 19:27 Makefile
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls .hd[Kidden
.hidden 
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls tests Makefile src LICENSE
LICENSE Makefile 

src:
cp.cpp[0m  hw0.cpp[0m  ls.cpp[0m  Timer.h[0m  

tests:
exec.script[0m  ls.script[0m  
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls -a tests MA[Kakefile -r[KR bin LICENS E
LICENSE Makefile 

./bin:
[34;100m.[0m  [34;100m..[0m  [32mcp[0m  [32mls[0m  [32mrshell[0m  

./tests:
[34;100m.[0m  [34;100m..[0m  exec.script[0m  ls.script[0m  
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ [K]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ #testinf [K[Kg ls when the file/dir passin[K[Ked in is outside of the current dir
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls /home/alexander/Documents/test
^[0m  ^^[0m  [34m*_*[0m  ^0$%[0m  3one[0m  865jkj46[0m  897894[0m  8raise[0m  ~8robots[0m  9.8.7.6.5[0m  
9nine9nine9nine[0m  a1b2[0m  aBcDeFg[0m  AbCdEfG[0m  [32ma.out[0m  a.Out[0m  [34mA.out[0m  a.zzzz[0m  b[0m  ___b[0m  
bb[0m  bbz[0m  bbzs[0m  bbzsf[0m  be[0m  bees[0m  c[0m  ^^car[0m  ^~car[0m  [34mdir[0m  donkey[0m  don.key[0m  
don..key[0m  extra[0m  ex.txt[0m  [34mfolder[0m  ^ghost[0m  ^^ghost[0m  ^~ghost[0m  [34mgo88away68[0m  
[34mgo89away67[0m  jhkhkj38278[0m  l.cpp[0m  ls.cpp[0m  lss.app[0m  [34mlss.cp[0m  lss.cpp[0m  lSs.cpp[0m  
lSS.cpp[0m  LsS.cpp[0m  LSs.cpp[0m  lss.pcc[0m  ls.txt[0m  [34mon1o[0m  on3e[0m  one[0m  one1[0m  one2[0m  
out.a[0m  pleasepleasepleasepleasepleasepleaseplease[0m  ^pops[0m  ~pops[0m  ^popssss[0m  
race[0m  ^race[0m  ^^race[0m  ^~race[0m  ~^race[0m  r~ace[0m  ra^ce[0m  ra~ce[0m  race^[0m  racff[0m  raf[0m  
^raise[0m  ^^raise[0m  ~raise[0m  raise^the~~woof[0m  rEadme[0m  README[0m  REDfm[0m  res[0m  Res[0m  
RES[0m  resume[0m  RESUME[0m  *r*raise[0m  tfqf[0m  this.9.is.8.a.7.file[0m  thisa[0m  
this.is.a.file[0m  [34mthree[0m  two[0m  z.aaaa[0m  ~zz[0m  
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls /home/alexander/Documents/test/A.out -lR
/home/alexander/Documents/test/A.out:
total 12
drwxrwxr-x 3 alexander alexander 4096 Nov 8 7:54 [34m^~^~^*@[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 8 7:53 [34mB.out[0m
-rw-rw-r-- 1 alexander alexander 0 Nov 8 7:53 junk
-rw-rw-r-- 1 alexander alexander 0 Nov 8 7:53 thejunk
-rw-rw-r-- 1 alexander alexander 0 Nov 8 7:53 Thejunk
drwxrwxr-x 2 alexander alexander 4096 Nov 8 7:53 [34m~^Thejunk~Thejunk[0m

/home/alexander/Documents/test/A.out/^~^~^*@:
total 4
drwxrwxr-x 3 alexander alexander 4096 Nov 8 7:54 [34m:B[0m
-rw-rw-r-- 1 alexander alexander 0 Nov 8 7:54 :D
-rw-rw-r-- 1 alexander alexander 0 Nov 8 7:54 T_T

/home/alexander/Documents/test/A.out/^~^~^*@/:B:
total 4
drwxrwxr-x 3 alexander alexander 4096 Nov 8 7:54 [34mrotten[0m
-rw-rw-r-- 1 alexander alexander 0 Nov 8 7:54 YOOOO

/home/alexander/Documents/test/A.out/^~^~^*@/:B/rotten:
total 4
drwxrwxr-x 2 alexander alexander 4096 Nov 8 7:54 [34mtomatoes[0m

/home/alexander/Documents/test/A.out/^~^~^*@/:B/rotten/tomatoes:
total 0

/home/alexander/Documents/test/A.out/B.out:
total 0

/home/alexander/Documents/test/A.out/~^Thejunk~Thejunk:
total 0
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ [K]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls /home/alexander/Documents/test/A.out -lR[K[K[K[K[K[K[K[K[Kthree/file.txt -l
-rw-rw-r-- 1 alexander alexander 0 Oct 28 7:49 /home/alexander/Documents/test/three/file.txt
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls /home/alexander/Documents/test/three/file.txt -l[K[K[K[K[K[K[K[K[K[K[K src Makefile /home/alexander[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K/home/alexander/Documents/test/three/file.txt
/home/alexander/Documents/test/three/file.txt Makefile 

/home/alexander/Documents/test/three:
file.txt[0m  justafile[0m  

src:
cp.cpp[0m  hw0.cpp[0m  ls.cpp[0m  Timer.h[0m  
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ #testing ls when one of the file/dir passed in does not exist
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls notafile
lstat: No such file or directory
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls notafile src notafile tests not [Kafile
lstat: No such file or directory
lstat: No such file or directory
lstat: No such file or directory
src:
cp.cpp[0m  hw0.cpp[0m  ls.cpp[0m  Timer.h[0m  

tests:
exec.script[0m  ls.script[0m  
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ #testing flag checking
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls -w
No such flag
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls -alR -w
No such flag
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls -alRw
No such flag
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls -alRw[K[K[K[KA
No such flag
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls -A[KL
No such flag
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls -L[Kr
No such flag
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls -ral
No such flag
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ #testing ls when [a[K[Kpassed '.' and ".."
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls .
[34mbin[0m  [32mbin_link[0m  LICENSE[0m  Makefile[0m  README.md[0m  [34msrc[0m  [34mtests[0m  
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls ..
[34mreleases[0m  [34mrshell[0m  [34mrshell-1[0m  
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ #testing ls when cl[Kaled form[K[Kr[K[Krom outside [K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K#testing ls when cale[Kled from outside current dir
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ cd ..
]0;alexander@Lahela: ~/cs100alexander@Lahela:~/cs100$ bin[K[K[K./bin[K[Kr[K[Krshell/bin/ls
[34mreleases[0m  [34mrshell[0m  [34mrshell-1[0m  
]0;alexander@Lahela: ~/cs100alexander@Lahela:~/cs100$ cd rshell
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ #testing recu[K[K[K[Kcur[K[Kr[K[Kru[K[K-Ra
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls /h[K[K[K[K[K[K[K[K[K#was[K[K[Kdid not test previouslt [K[Ky due to the wo[K[K[K[K[K[Kmy working directory containing .git[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[Kbin/ls /home/alexander/Documents/hidden_test -Ra/ -Ra
/home/alexander/Documents/hidden_test:
[34;100m.[0m  [34;100m..[0m  [34;100m.subdir[0m  

/home/alexander/Documents/hidden_test/.subdir:
[34;100m.[0m  [34;100m..[0m  [34;100m.subsubdir[0m  

/home/alexander/Documents/hidden_test/.subdir/.subsubdir:
[34;100m.[0m  [34;100m..[0m  [34;100m.subsubdir[0m  

/home/alexander/Documents/hidden_test/.subdir/.subsubdir/.subsubdir:
[34;100m.[0m  [34;100m..[0m  
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ #this concludes testing[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[Kthis concludes tesin[K[Kting
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ exit
exit

Script done on Tue 11 Nov 2014 08:37:08 PM PST
