Script started on Sun 09 Nov 2014 05:17:25 PM PST
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ #testing ls in current dir
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls
[34mbin[0m  LICENSE  [32mLiLink[0m  Makefile  README.md  [34msrc[0m  [32msrcLink[0m  [34mtests[0m  
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls -a
[34m.[0m  [34m..[0m  [34mbin[0m  [34m.git[0m  .hidden  LICENSE  [32mLiLink[0m  Makefile  README.md  [34msrc[0m  [32msrcLink[0m  
[34mtests[0m  
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls -l
total 24
drwxrwxr-x 2 alexander alexander 4096 Nov 9 17:14 [34mbin[0m
-rw-rw-r-- 1 alexander alexander 1486 Nov 7 23:57 LICENSE
lrwxrwxrwx 1 alexander alexander 7 Nov 9 7:51 [32mLiLink[0m
-rw-rw-r-- 1 alexander alexander 410 Nov 7 23:57 Makefile
-rw-rw-r-- 1 alexander alexander 2176 Nov 7 23:57 README.md
drwxrwxr-x 2 alexander alexander 4096 Nov 9 17:15 [34msrc[0m
lrwxrwxrwx 1 alexander alexander 3 Nov 9 7:50 [32msrcLink[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 9 17:17 [34mtests[0m
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ [K]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls -R
.:
[34mbin[0m  LICENSE  [32mLiLink[0m  Makefile  README.md  [34msrc[0m  [32msrcLink[0m  [34mtests[0m  

./bin:
[32mls[0m  [32mrshell[0m  

./src:
hw0.cpp  ls.cpp  

./tests:
exec.script  ls.script  
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ #testing ls when passing in different  combinations of flags
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ ni[K[Kbin/ls -a l[K-l
total 36
drwxrwxr-x 6 alexander alexander 4096 Nov 9 17:14 [34m.[0m
drwxrwxr-x 5 alexander alexander 4096 Nov 8 9:44 [34m..[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 9 17:14 [34mbin[0m
drwxrwxr-x 8 alexander alexander 4096 Nov 9 17:16 [34m.git[0m
-rw-rw-r-- 1 alexander alexander 0 Nov 9 16:53 .hidden
-rw-rw-r-- 1 alexander alexander 1486 Nov 7 23:57 LICENSE
lrwxrwxrwx 1 alexander alexander 7 Nov 9 7:51 [32mLiLink[0m
-rw-rw-r-- 1 alexander alexander 410 Nov 7 23:57 Makefile
-rw-rw-r-- 1 alexander alexander 2176 Nov 7 23:57 README.md
drwxrwxr-x 2 alexander alexander 4096 Nov 9 17:15 [34msrc[0m
lrwxrwxrwx 1 alexander alexander 3 Nov 9 7:50 [32msrcLink[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 9 17:17 [34mtests[0m
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls -la
total 36
drwxrwxr-x 6 alexander alexander 4096 Nov 9 17:14 [34m.[0m
drwxrwxr-x 5 alexander alexander 4096 Nov 8 9:44 [34m..[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 9 17:14 [34mbin[0m
drwxrwxr-x 8 alexander alexander 4096 Nov 9 17:16 [34m.git[0m
-rw-rw-r-- 1 alexander alexander 0 Nov 9 16:53 .hidden
-rw-rw-r-- 1 alexander alexander 1486 Nov 7 23:57 LICENSE
lrwxrwxrwx 1 alexander alexander 7 Nov 9 7:51 [32mLiLink[0m
-rw-rw-r-- 1 alexander alexander 410 Nov 7 23:57 Makefile
-rw-rw-r-- 1 alexander alexander 2176 Nov 7 23:57 README.md
drwxrwxr-x 2 alexander alexander 4096 Nov 9 17:15 [34msrc[0m
lrwxrwxrwx 1 alexander alexander 3 Nov 9 7:50 [32msrcLink[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 9 17:17 [34mtests[0m
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls -Rl
.:
total 24
drwxrwxr-x 2 alexander alexander 4096 Nov 9 17:14 [34mbin[0m
-rw-rw-r-- 1 alexander alexander 1486 Nov 7 23:57 LICENSE
lrwxrwxrwx 1 alexander alexander 7 Nov 9 7:51 [32mLiLink[0m
-rw-rw-r-- 1 alexander alexander 410 Nov 7 23:57 Makefile
-rw-rw-r-- 1 alexander alexander 2176 Nov 7 23:57 README.md
drwxrwxr-x 2 alexander alexander 4096 Nov 9 17:15 [34msrc[0m
lrwxrwxrwx 1 alexander alexander 3 Nov 9 7:50 [32msrcLink[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 9 17:17 [34mtests[0m

./bin:
total 196
-rwxrwxr-x 1 alexander alexander 153990 Nov 9 17:14 [32mls[0m
-rwxrwxr-x 1 alexander alexander 41774 Nov 9 17:14 [32mrshell[0m

./src:
total 32
-rw-rw-r-- 1 alexander alexander 12361 Nov 9 13:11 hw0.cpp
-rw-rw-r-- 1 alexander alexander 16285 Nov 9 17:13 ls.cpp

./tests:
total 20
-rw-rw-r-- 1 alexander alexander 15164 Nov 7 23:57 exec.script
-rw-rw-r-- 1 alexander alexander 4096 Nov 9 17:19 ls.script
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls -a -lR
.:
total 36
drwxrwxr-x 6 alexander alexander 4096 Nov 9 17:14 [34m.[0m
drwxrwxr-x 5 alexander alexander 4096 Nov 8 9:44 [34m..[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 9 17:14 [34mbin[0m
drwxrwxr-x 8 alexander alexander 4096 Nov 9 17:16 [34m.git[0m
-rw-rw-r-- 1 alexander alexander 0 Nov 9 16:53 .hidden
-rw-rw-r-- 1 alexander alexander 1486 Nov 7 23:57 LICENSE
lrwxrwxrwx 1 alexander alexander 7 Nov 9 7:51 [32mLiLink[0m
-rw-rw-r-- 1 alexander alexander 410 Nov 7 23:57 Makefile
-rw-rw-r-- 1 alexander alexander 2176 Nov 7 23:57 README.md
drwxrwxr-x 2 alexander alexander 4096 Nov 9 17:15 [34msrc[0m
lrwxrwxrwx 1 alexander alexander 3 Nov 9 7:50 [32msrcLink[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 9 17:17 [34mtests[0m

./bin:
total 204
drwxrwxr-x 2 alexander alexander 4096 Nov 9 17:14 [34m.[0m
drwxrwxr-x 6 alexander alexander 4096 Nov 9 17:14 [34m..[0m
-rwxrwxr-x 1 alexander alexander 153990 Nov 9 17:14 [32mls[0m
-rwxrwxr-x 1 alexander alexander 41774 Nov 9 17:14 [32mrshell[0m

./.git:
total 56
drwxrwxr-x 8 alexander alexander 4096 Nov 9 17:16 [34m.[0m
drwxrwxr-x 6 alexander alexander 4096 Nov 9 17:14 [34m..[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 7 23:57 [34mbranches[0m
-rw-rw-r-- 1 alexander alexander 61 Nov 9 17:15 COMMIT_EDITMSG
-rw-rw-r-- 1 alexander alexander 255 Nov 7 23:57 config
-rw-rw-r-- 1 alexander alexander 73 Nov 7 23:57 description
-rw-rw-r-- 1 alexander alexander 19 Nov 7 23:57 HEAD
drwxrwxr-x 2 alexander alexander 4096 Nov 7 23:57 [34mhooks[0m
-rw-rw-r-- 1 alexander alexander 488 Nov 9 17:15 index
drwxrwxr-x 2 alexander alexander 4096 Nov 7 23:57 [34minfo[0m
drwxrwxr-x 3 alexander alexander 4096 Nov 7 23:57 [34mlogs[0m
drwxrwxr-x 22 alexander alexander 4096 Nov 9 17:15 [34mobjects[0m
-rw-rw-r-- 1 alexander alexander 292 Nov 7 23:57 packed-refs
drwxrwxr-x 5 alexander alexander 4096 Nov 7 23:57 [34mrefs[0m

./.git/branches:
total 8
drwxrwxr-x 2 alexander alexander 4096 Nov 7 23:57 [34m.[0m
drwxrwxr-x 8 alexander alexander 4096 Nov 9 17:16 [34m..[0m

./.git/hooks:
total 48
drwxrwxr-x 2 alexander alexander 4096 Nov 7 23:57 [34m.[0m
drwxrwxr-x 8 alexander alexander 4096 Nov 9 17:16 [34m..[0m
-rwxrwxr-x 1 alexander alexander 452 Nov 7 23:57 [32mapplypatch-msg.sample[0m
-rwxrwxr-x 1 alexander alexander 896 Nov 7 23:57 [32mcommit-msg.sample[0m
-rwxrwxr-x 1 alexander alexander 189 Nov 7 23:57 [32mpost-update.sample[0m
-rwxrwxr-x 1 alexander alexander 398 Nov 7 23:57 [32mpre-applypatch.sample[0m
-rwxrwxr-x 1 alexander alexander 1642 Nov 7 23:57 [32mpre-commit.sample[0m
-rwxrwxr-x 1 alexander alexander 1239 Nov 7 23:57 [32mprepare-commit-msg.sample[0m
-rwxrwxr-x 1 alexander alexander 1352 Nov 7 23:57 [32mpre-push.sample[0m
-rwxrwxr-x 1 alexander alexander 4898 Nov 7 23:57 [32mpre-rebase.sample[0m
-rwxrwxr-x 1 alexander alexander 3611 Nov 7 23:57 [32mupdate.sample[0m

./.git/info:
total 12
drwxrwxr-x 2 alexander alexander 4096 Nov 7 23:57 [34m.[0m
drwxrwxr-x 8 alexander alexander 4096 Nov 9 17:16 [34m..[0m
-rw-rw-r-- 1 alexander alexander 240 Nov 7 23:57 exclude

./.git/logs:
total 16
drwxrwxr-x 3 alexander alexander 4096 Nov 7 23:57 [34m.[0m
drwxrwxr-x 8 alexander alexander 4096 Nov 9 17:16 [34m..[0m
-rw-rw-r-- 1 alexander alexander 1086 Nov 9 17:15 HEAD
drwxrwxr-x 4 alexander alexander 4096 Nov 7 23:57 [34mrefs[0m

./.git/logs/refs:
total 16
drwxrwxr-x 4 alexander alexander 4096 Nov 7 23:57 [34m.[0m
drwxrwxr-x 3 alexander alexander 4096 Nov 7 23:57 [34m..[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 7 23:57 [34mheads[0m
drwxrwxr-x 3 alexander alexander 4096 Nov 7 23:57 [34mremotes[0m

./.git/logs/refs/heads:
total 12
drwxrwxr-x 2 alexander alexander 4096 Nov 7 23:57 [34m.[0m
drwxrwxr-x 4 alexander alexander 4096 Nov 7 23:57 [34m..[0m
-rw-rw-r-- 1 alexander alexander 1086 Nov 9 17:15 ls

./.git/logs/refs/remotes:
total 12
drwxrwxr-x 3 alexander alexander 4096 Nov 7 23:57 [34m.[0m
drwxrwxr-x 4 alexander alexander 4096 Nov 7 23:57 [34m..[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 7 23:57 [34morigin[0m

./.git/logs/refs/remotes/origin:
total 12
drwxrwxr-x 2 alexander alexander 4096 Nov 7 23:57 [34m.[0m
drwxrwxr-x 3 alexander alexander 4096 Nov 7 23:57 [34m..[0m
-rw-rw-r-- 1 alexander alexander 185 Nov 7 23:57 HEAD

./.git/objects:
total 88
drwxrwxr-x 22 alexander alexander 4096 Nov 9 17:15 [34m.[0m
drwxrwxr-x 8 alexander alexander 4096 Nov 9 17:16 [34m..[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 9 17:15 [34m02[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 9 7:54 [34m06[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 8 8:39 [34m19[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 8 8:38 [34m29[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 9 17:15 [34m2c[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 9 7:54 [34m36[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 8 8:35 [34m52[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 9 7:53 [34m5a[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 8 8:35 [34m5b[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 9 17:15 [34m5d[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 8 8:38 [34m62[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 8 8:39 [34m77[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 8 8:35 [34m7a[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 9 17:15 [34m81[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 9 7:54 [34m91[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 8 8:35 [34m9a[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 8 8:39 [34ma0[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 8 8:38 [34md7[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 7 23:57 [34minfo[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 7 23:57 [34mpack[0m

./.git/objects/02:
total 12
drwxrwxr-x 2 alexander alexander 4096 Nov 9 17:15 [34m.[0m
drwxrwxr-x 22 alexander alexander 4096 Nov 9 17:15 [34m..[0m
-r--r--r-- 1 alexander alexander 198 Nov 9 17:15 a880a760118ed7b23d741239fb68b1238b8efa

./.git/objects/06:
total 12
drwxrwxr-x 2 alexander alexander 4096 Nov 9 7:54 [34m.[0m
drwxrwxr-x 22 alexander alexander 4096 Nov 9 17:15 [34m..[0m
-r--r--r-- 1 alexander alexander 177 Nov 9 7:54 1162da9cab967bc80293ae7e2853eb987a6aa6

./.git/objects/19:
total 12
drwxrwxr-x 2 alexander alexander 4096 Nov 8 8:39 [34m.[0m
drwxrwxr-x 22 alexander alexander 4096 Nov 9 17:15 [34m..[0m
-r--r--r-- 1 alexander alexander 170 Nov 8 8:39 c527549742260d820ac75a5de92301e88d9531

./.git/objects/29:
total 12
drwxrwxr-x 2 alexander alexander 4096 Nov 8 8:38 [34m.[0m
drwxrwxr-x 22 alexander alexander 4096 Nov 9 17:15 [34m..[0m
-r--r--r-- 1 alexander alexander 173 Nov 8 8:38 5cad5193322164e689d50a7b2b0867e66afb90

./.git/objects/2c:
total 12
drwxrwxr-x 2 alexander alexander 4096 Nov 9 17:15 [34m.[0m
drwxrwxr-x 22 alexander alexander 4096 Nov 9 17:15 [34m..[0m
-r--r--r-- 1 alexander alexander 177 Nov 9 17:15 02dc3d4b267bb4f30fa9b4f6dd8acf9473092c

./.git/objects/36:
total 12
drwxrwxr-x 2 alexander alexander 4096 Nov 9 7:54 [34m.[0m
drwxrwxr-x 22 alexander alexander 4096 Nov 9 17:15 [34m..[0m
-r--r--r-- 1 alexander alexander 180 Nov 9 7:54 2473d6b5893cd2e68a34d1ddbf3deea51a6a2f

./.git/objects/52:
total 12
drwxrwxr-x 2 alexander alexander 4096 Nov 8 8:35 [34m.[0m
drwxrwxr-x 22 alexander alexander 4096 Nov 9 17:15 [34m..[0m
-r--r--r-- 1 alexander alexander 79 Nov 8 8:35 1b02e61880a256eaf24e91080c666f4337a8a1

./.git/objects/5a:
total 12
drwxrwxr-x 2 alexander alexander 4096 Nov 9 7:53 [34m.[0m
drwxrwxr-x 22 alexander alexander 4096 Nov 9 17:15 [34m..[0m
-r--r--r-- 1 alexander alexander 2570 Nov 9 7:53 1735c67c5c453cc23ff8bd0b8fa036241a4eac

./.git/objects/5b:
total 12
drwxrwxr-x 2 alexander alexander 4096 Nov 8 8:35 [34m.[0m
drwxrwxr-x 22 alexander alexander 4096 Nov 9 17:15 [34m..[0m
-r--r--r-- 1 alexander alexander 2561 Nov 8 8:35 9e3ad7d6c59ef0d7bc8ea5624b136147796d79

./.git/objects/5d:
total 12
drwxrwxr-x 2 alexander alexander 4096 Nov 9 17:15 [34m.[0m
drwxrwxr-x 22 alexander alexander 4096 Nov 9 17:15 [34m..[0m
-r--r--r-- 1 alexander alexander 79 Nov 9 17:15 fbddb9269578be7f494bd5fd37db07ee1b4cc4

./.git/objects/62:
total 12
drwxrwxr-x 2 alexander alexander 4096 Nov 8 8:38 [34m.[0m
drwxrwxr-x 22 alexander alexander 4096 Nov 9 17:15 [34m..[0m
-r--r--r-- 1 alexander alexander 178 Nov 8 8:38 d4690041477d6a103edf7fae4fcc76912fb13e

./.git/objects/77:
total 12
drwxrwxr-x 2 alexander alexander 4096 Nov 8 8:39 [34m.[0m
drwxrwxr-x 22 alexander alexander 4096 Nov 9 17:15 [34m..[0m
-r--r--r-- 1 alexander alexander 177 Nov 8 8:39 138fb22d8076992bc40d84ee05530e5e0efc9d

./.git/objects/7a:
total 12
drwxrwxr-x 2 alexander alexander 4096 Nov 8 8:35 [34m.[0m
drwxrwxr-x 22 alexander alexander 4096 Nov 9 17:15 [34m..[0m
-r--r--r-- 1 alexander alexander 185 Nov 8 8:35 a063e7e46f0914cd17fa072189ca10e2437df7

./.git/objects/81:
total 12
drwxrwxr-x 2 alexander alexander 4096 Nov 9 17:15 [34m.[0m
drwxrwxr-x 22 alexander alexander 4096 Nov 9 17:15 [34m..[0m
-r--r--r-- 1 alexander alexander 2911 Nov 9 17:15 65ac1d9213e378b65d9f5354c956fe1e1db3b5

./.git/objects/91:
total 12
drwxrwxr-x 2 alexander alexander 4096 Nov 9 7:54 [34m.[0m
drwxrwxr-x 22 alexander alexander 4096 Nov 9 17:15 [34m..[0m
-r--r--r-- 1 alexander alexander 79 Nov 9 7:54 b32a4e192ab9a56376db02e2c22843bda2bd10

./.git/objects/9a:
total 12
drwxrwxr-x 2 alexander alexander 4096 Nov 8 8:35 [34m.[0m
drwxrwxr-x 22 alexander alexander 4096 Nov 9 17:15 [34m..[0m
-r--r--r-- 1 alexander alexander 177 Nov 8 8:35 5a15f333ba55ed3a4d3827af711a8f0d7f9207

./.git/objects/a0:
total 12
drwxrwxr-x 2 alexander alexander 4096 Nov 8 8:39 [34m.[0m
drwxrwxr-x 22 alexander alexander 4096 Nov 9 17:15 [34m..[0m
-r--r--r-- 1 alexander alexander 79 Nov 8 8:39 9370e2a30ebc26bbf280fde04bd601ae811137

./.git/objects/d7:
total 12
drwxrwxr-x 2 alexander alexander 4096 Nov 8 8:38 [34m.[0m
drwxrwxr-x 22 alexander alexander 4096 Nov 9 17:15 [34m..[0m
-r--r--r-- 1 alexander alexander 107 Nov 8 8:38 0750ec57c0e096b3b07b51e29cd9b62aa8e4a2

./.git/objects/info:
total 8
drwxrwxr-x 2 alexander alexander 4096 Nov 7 23:57 [34m.[0m
drwxrwxr-x 22 alexander alexander 4096 Nov 9 17:15 [34m..[0m

./.git/objects/pack:
total 80
drwxrwxr-x 2 alexander alexander 4096 Nov 7 23:57 [34m.[0m
drwxrwxr-x 22 alexander alexander 4096 Nov 9 17:15 [34m..[0m
-r--r--r-- 1 alexander alexander 9836 Nov 7 23:57 pack-c6d99528060a41f0d956ae18c6241f38590f0788.idx
-r--r--r-- 1 alexander alexander 61173 Nov 7 23:57 pack-c6d99528060a41f0d956ae18c6241f38590f0788.pack

./.git/refs:
total 20
drwxrwxr-x 5 alexander alexander 4096 Nov 7 23:57 [34m.[0m
drwxrwxr-x 8 alexander alexander 4096 Nov 9 17:16 [34m..[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 9 17:15 [34mheads[0m
drwxrwxr-x 3 alexander alexander 4096 Nov 7 23:57 [34mremotes[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 7 23:57 [34mtags[0m

./.git/refs/heads:
total 12
drwxrwxr-x 2 alexander alexander 4096 Nov 9 17:15 [34m.[0m
drwxrwxr-x 5 alexander alexander 4096 Nov 7 23:57 [34m..[0m
-rw-rw-r-- 1 alexander alexander 41 Nov 9 17:15 ls

./.git/refs/remotes:
total 12
drwxrwxr-x 3 alexander alexander 4096 Nov 7 23:57 [34m.[0m
drwxrwxr-x 5 alexander alexander 4096 Nov 7 23:57 [34m..[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 7 23:57 [34morigin[0m

./.git/refs/remotes/origin:
total 12
drwxrwxr-x 2 alexander alexander 4096 Nov 7 23:57 [34m.[0m
drwxrwxr-x 3 alexander alexander 4096 Nov 7 23:57 [34m..[0m
-rw-rw-r-- 1 alexander alexander 32 Nov 7 23:57 HEAD

./.git/refs/tags:
total 8
drwxrwxr-x 2 alexander alexander 4096 Nov 7 23:57 [34m.[0m
drwxrwxr-x 5 alexander alexander 4096 Nov 7 23:57 [34m..[0m

./src:
total 40
drwxrwxr-x 2 alexander alexander 4096 Nov 9 17:15 [34m.[0m
drwxrwxr-x 6 alexander alexander 4096 Nov 9 17:14 [34m..[0m
-rw-rw-r-- 1 alexander alexander 12361 Nov 9 13:11 hw0.cpp
-rw-rw-r-- 1 alexander alexander 16285 Nov 9 17:13 ls.cpp

./tests:
total 56
drwxrwxr-x 2 alexander alexander 4096 Nov 9 17:17 [34m.[0m
drwxrwxr-x 6 alexander alexander 4096 Nov 9 17:14 [34m..[0m
-rw-rw-r-- 1 alexander alexander 15164 Nov 7 23:57 exec.script
-rw-rw-r-- 1 alexander alexander 16384 Nov 9 17:19 ls.script
-rw-r--r-- 1 alexander alexander 16384 Nov 9 17:14 .ls.script.swp
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ #testing ls when passing in i[Ki[Kfile/dir w [A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[K
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Ci n current dir
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls src
hw0.cpp  ls.cpp  
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls ./src
hw0.cpp  ls.cpp  
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls ./src/
hw0.cpp  ls.cpp  
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls ./[K[Ksrc/
hw0.cpp  ls.cpp  
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls src tests
src:
hw0.cpp  ls.cpp  

tests:
exec.script  ls.script  
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls src tests -al
src:
total 40
drwxrwxr-x 2 alexander alexander 4096 Nov 9 17:15 [34m.[0m
drwxrwxr-x 6 alexander alexander 4096 Nov 9 17:14 [34m..[0m
-rw-rw-r-- 1 alexander alexander 12361 Nov 9 13:11 hw0.cpp
-rw-rw-r-- 1 alexander alexander 16285 Nov 9 17:13 ls.cpp

tests:
total 56
drwxrwxr-x 2 alexander alexander 4096 Nov 9 17:17 [34m.[0m
drwxrwxr-x 6 alexander alexander 4096 Nov 9 17:14 [34m..[0m
-rw-rw-r-- 1 alexander alexander 15164 Nov 7 23:57 exec.script
-rw-rw-r-- 1 alexander alexander 16384 Nov 9 17:19 ls.script
-rw-r--r-- 1 alexander alexander 16384 Nov 9 17:14 .ls.script.swp
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls Makefile
Makefile 
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls Mae[KkefileLIC[K[K[K LICNESE[K[K[K[KENSE
LICENSE Makefile 
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls ./Makefile LICENSE README.md
LICENSE ./Makefile README.md 
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ ~bin/ls ./Makefile LICENSE README.md -l [A
-rw-rw-r-- 1 alexander alexander 1486 Nov 7 23:57 LICENSE
-rw-rw-r-- 1 alexander alexander 410 Nov 7 23:57 ./Makefile
-rw-rw-r-- 1 alexander alexander 2176 Nov 7 23:57 README.md
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls ./bin/exec.script -l
lstat: No such file or directory
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls ./bin/exec.script -l[C[C[C[C[C[C[C[C[C[C[C[C[C[1P[1P[1P[1@t[1@e[1@s[1@t[1@s
-rw-rw-r-- 1 alexander alexander 15164 Nov 7 23:57 ./tests/exec.script
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls ./tests/exec.script -l[1P -l[1P -l[1P -l[1P -l[1P -l[1P -l[1P -l[1P -l[1P -l[1P -l[1P -l[1P -l[1P -l[1P -l[1P -l[1P -l[1P -lb -li -ln -l/ -ll -ls -l
-rwxrwxr-x 1 alexander alexander 153990 Nov 9 17:14 [32m./bin/ls
[0m]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls Makefile src t[KLICENSE tests READ ME.md bin
LICENSE Makefile README.md 

bin:
[32mls[0m  [32mrshell[0m  

src:
hw0.cpp  ls.cpp  

tests:
exec.script  ls.script  
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls Makefile src LICENSE tests READMME.md bin -l
-rw-rw-r-- 1 alexander alexander 1486 Nov 7 23:57 LICENSE
-rw-rw-r-- 1 alexander alexander 410 Nov 7 23:57 Makefile
-rw-rw-r-- 1 alexander alexander 2176 Nov 7 23:57 README.md

bin:
total 196
-rwxrwxr-x 1 alexander alexander 153990 Nov 9 17:14 [32mls[0m
-rwxrwxr-x 1 alexander alexander 41774 Nov 9 17:14 [32mrshell[0m

src:
total 32
-rw-rw-r-- 1 alexander alexander 12361 Nov 9 13:11 hw0.cpp
-rw-rw-r-- 1 alexander alexander 16285 Nov 9 17:13 ls.cpp

tests:
total 36
-rw-rw-r-- 1 alexander alexander 15164 Nov 7 23:57 exec.script
-rw-rw-r-- 1 alexander alexander 20480 Nov 9 17:29 ls.script
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ #testing ls when passing file/dir not  in the cr[Kurrent dir
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls /home/alexander/Documents/test
^  ^^  [34m*_*[0m  ^0$%  3one  865jkj46  897894  8raise  ~8robots  9.8.7.6.5  
9nine9nine9nine  a1b2  aBcDeFg  AbCdEfG  [32ma.out[0m  a.Out  [34mA.out[0m  a.zzzz  ___b  
bees  c  ^^car  ^~car  [34mdir[0m  donkey  don.key  don..key  extra  ex.txt  [34mfolder[0m  
^ghost  ^^ghost  ^~ghost  [34mgo88away68[0m  [34mgo89away67[0m  jhkhkj38278  l.cpp  ls.cpp  
lss.app  [34mlss.cp[0m  lss.cpp  lSs.cpp  lSS.cpp  LsS.cpp  LSs.cpp  lss.pcc  ls.txt  
[34mon1o[0m  on3e  one  one1  one2  out.a  ^pops  ~pops  ^popssss  race  ^race  
^^race  ^~race  ~^race  r~ace  ra^ce  ra~ce  race^  racff  raf  ^raise  
^^raise  ~raise  raise^the~~woof  rEadme  README  REDfm  res  Res  RES  
resume  RESUME  *r*raise  this.9.is.8.a.7.file  this.is.a.file  [34mthree[0m  two  
z.aaaa  ~zz  
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ [K]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls /home/alexander/Documents/test -l
total 96
-rw-rw-r-- 1 alexander alexander 0 Nov 7 22:12 ^
-rw-rw-r-- 1 alexander alexander 0 Nov 7 22:12 ^^
drwxrwxr-x 3 alexander alexander 4096 Nov 7 19:18 [34m*_*[0m
-rw-rw-r-- 1 alexander alexander 0 Nov 7 18:18 ^0$%
-rw-rw-r-- 1 alexander alexander 0 Nov 7 18:46 3one
-rw-rw-r-- 1 alexander alexander 0 Nov 7 18:18 865jkj46
-rw-rw-r-- 1 alexander alexander 0 Nov 7 18:17 897894
-rw-rw-r-- 1 alexander alexander 0 Nov 7 21:02 8raise
-rw-rw-r-- 1 alexander alexander 0 Nov 7 21:17 ~8robots
-rw-rw-r-- 1 alexander alexander 0 Nov 7 18:47 9.8.7.6.5
-rw-rw-r-- 1 alexander alexander 0 Nov 7 19:27 9nine9nine9nine
-rw-rw-r-- 1 alexander alexander 0 Nov 7 18:17 a1b2
-rw-rw-r-- 1 alexander alexander 0 Nov 7 18:49 aBcDeFg
-rw-rw-r-- 1 alexander alexander 0 Nov 7 18:49 AbCdEfG
-rwxrwxr-x 1 alexander alexander 49630 Oct 28 8:02 [32ma.out[0m
-rw-rw-r-- 1 alexander alexander 0 Nov 7 18:47 a.Out
drwxrwxr-x 5 alexander alexander 4096 Nov 8 7:53 [34mA.out[0m
-rw-rw-r-- 1 alexander alexander 0 Nov 7 18:48 a.zzzz
-rw-rw-r-- 1 alexander alexander 0 Nov 7 23:38 ___b
-rw-rw-r-- 1 alexander alexander 0 Nov 9 17:32 bees
-rw-rw-r-- 1 alexander alexander 0 Nov 7 22:12 c
-rw-rw-r-- 1 alexander alexander 0 Nov 7 22:10 ^^car
-rw-rw-r-- 1 alexander alexander 0 Nov 7 22:10 ^~car
drwxrwxr-x 3 alexander alexander 4096 Oct 28 7:48 [34mdir[0m
-rw-rw-r-- 1 alexander alexander 0 Nov 7 22:05 donkey
-rw-rw-r-- 1 alexander alexander 0 Nov 7 22:05 don.key
-rw-rw-r-- 1 alexander alexander 0 Nov 7 22:05 don..key
-rw-rw-r-- 1 alexander alexander 0 Oct 28 7:52 extra
-rw-rw-r-- 1 alexander alexander 0 Oct 27 19:37 ex.txt
drwxrwxr-x 2 alexander alexander 4096 Oct 28 7:49 [34mfolder[0m
-rw-rw-r-- 1 alexander alexander 0 Nov 7 23:25 ^ghost
-rw-rw-r-- 1 alexander alexander 0 Nov 7 23:26 ^^ghost
-rw-rw-r-- 1 alexander alexander 0 Nov 7 23:26 ^~ghost
drwxrwxr-x 2 alexander alexander 4096 Nov 8 7:52 [34mgo88away68[0m
drwxrwxr-x 2 alexander alexander 4096 Nov 8 7:52 [34mgo89away67[0m
-rw-rw-r-- 1 alexander alexander 0 Nov 7 18:18 jhkhkj38278
-rw-rw-r-- 1 alexander alexander 0 Nov 7 18:13 l.cpp
-rw-rw-r-- 1 alexander alexander 4113 Oct 28 8:02 ls.cpp
-rw-rw-r-- 1 alexander alexander 0 Nov 7 18:17 lss.app
drwxrwxr-x 2 alexander alexander 4096 Nov 7 18:46 [34mlss.cp[0m
-rw-rw-r-- 1 alexander alexander 0 Nov 7 18:14 lss.cpp
-rw-rw-r-- 1 alexander alexander 0 Nov 7 19:19 lSs.cpp
-rw-rw-r-- 1 alexander alexander 0 Nov 7 19:19 lSS.cpp
-rw-rw-r-- 1 alexander alexander 0 Nov 7 19:19 LsS.cpp
-rw-rw-r-- 1 alexander alexander 0 Nov 7 19:19 LSs.cpp
-rw-rw-r-- 1 alexander alexander 0 Nov 7 19:19 lss.pcc
-rw-rw-r-- 1 alexander alexander 0 Nov 7 18:14 ls.txt
drwxrwxr-x 2 alexander alexander 4096 Nov 7 18:46 [34mon1o[0m
-rw-rw-r-- 1 alexander alexander 0 Nov 7 18:46 on3e
-rw-rw-r-- 1 alexander alexander 0 Oct 28 7:49 one
-rw-rw-r-- 1 alexander alexander 0 Nov 7 18:46 one1
-rw-rw-r-- 1 alexander alexander 0 Nov 7 18:46 one2
-rw-rw-r-- 1 alexander alexander 0 Nov 7 18:46 out.a
-rw-rw-r-- 1 alexander alexander 0 Nov 7 19:35 ^pops
-rw-rw-r-- 1 alexander alexander 0 Nov 7 19:46 ~pops
-rw-rw-r-- 1 alexander alexander 0 Nov 7 23:14 ^popssss
-rw-rw-r-- 1 alexander alexander 0 Nov 7 22:12 race
-rw-rw-r-- 1 alexander alexander 0 Nov 7 22:12 ^race
-rw-rw-r-- 1 alexander alexander 0 Nov 7 22:12 ^^race
-rw-rw-r-- 1 alexander alexander 0 Nov 7 22:13 ^~race
-rw-rw-r-- 1 alexander alexander 0 Nov 7 22:13 ~^race
-rw-rw-r-- 1 alexander alexander 0 Nov 7 23:37 r~ace
-rw-rw-r-- 1 alexander alexander 0 Nov 7 23:29 ra^ce
-rw-rw-r-- 1 alexander alexander 0 Nov 7 22:11 ra~ce
-rw-rw-r-- 1 alexander alexander 0 Nov 7 23:28 race^
-rw-rw-r-- 1 alexander alexander 0 Nov 7 23:29 racff
-rw-rw-r-- 1 alexander alexander 0 Nov 7 23:30 raf
-rw-rw-r-- 1 alexander alexander 0 Nov 7 19:21 ^raise
-rw-rw-r-- 1 alexander alexander 0 Nov 7 19:21 ^^raise
-rw-rw-r-- 1 alexander alexander 0 Nov 7 19:22 ~raise
-rw-rw-r-- 1 alexander alexander 0 Nov 7 19:21 raise^the~~woof
-rw-rw-r-- 1 alexander alexander 0 Nov 7 11:11 rEadme
-rw-rw-r-- 1 alexander alexander 0 Oct 27 19:37 README
-rw-rw-r-- 1 alexander alexander 0 Nov 7 11:11 REDfm
-rw-rw-r-- 1 alexander alexander 0 Nov 7 11:11 res
-rw-rw-r-- 1 alexander alexander 0 Nov 7 11:11 Res
-rw-rw-r-- 1 alexander alexander 0 Nov 7 11:11 RES
-rw-rw-r-- 1 alexander alexander 0 Nov 7 11:11 resume
-rw-rw-r-- 1 alexander alexander 0 Nov 7 11:11 RESUME
-rw-rw-r-- 1 alexander alexander 0 Nov 7 19:21 *r*raise
-rw-rw-r-- 1 alexander alexander 0 Nov 7 18:47 this.9.is.8.a.7.file
-rw-rw-r-- 1 alexander alexander 0 Nov 7 18:47 this.is.a.file
drwxrwxr-x 2 alexander alexander 4096 Oct 28 7:49 [34mthree[0m
-rw-rw-r-- 1 alexander alexander 0 Oct 28 7:49 two
-rw-rw-r-- 1 alexander alexander 0 Nov 7 18:48 z.aaaa
-rw-rw-r-- 1 alexander alexander 0 Nov 7 23:27 ~zz
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls /home/alexander/Documents/test -l[Ka
^  ^^  [34m.[0m  [34m..[0m  [34m*_*[0m  ^0$%  3one  865jkj46  [34m.8974[0m  897894  8raise  ~8robots  
9.8.7.6.5  9nine9nine9nine  a1b2  aBcDeFg  AbCdEfG  [32ma.out[0m  a.Out  [34mA.out[0m  
a.zzzz  ___b  bees  c  ^^car  ^~car  [34mdir[0m  donkey  don.key  don..key  extra  
ex.txt  [34mfolder[0m  ^ghost  ^^ghost  ^~ghost  [34mgo88away68[0m  [34mgo89away67[0m  [34m.goaway[0m  
jhkhkj38278  l.cpp  [34m.look...at...that[0m  .ls.cpp  ls.cpp  lss.app  [34mlss.cp[0m  
lss.cpp  lSs.cpp  lSS.cpp  LsS.cpp  LSs.cpp  lss.pcc  ls.txt  [34mon1o[0m  .on2e  
on3e  one  one1  one2  out.a  ^pops  ~pops  ^popssss  race  ^race  ^^race  
^~race  ~^race  .race  r~ace  ra^ce  ra~ce  race^  racff  raf  ^raise  
^^raise  ~raise  .raise^the~~woof  raise^the~~woof  rEadme  README  REDfm  
res  Res  RES  resume  RESUME  *r*raise  this.9.is.8.a.7.file  this.is.a.file  
[34mthree[0m  two  z.aaaa  ~zz  
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls /home/alexander/Documents/test -a[KRa[K[K[K[1@-[1@R[1@a[1@ 
/home/alexander/Documents/test:
^  ^^  [34m.[0m  [34m..[0m  [34m*_*[0m  ^0$%  3one  865jkj46  [34m.8974[0m  897894  8raise  ~8robots  
9.8.7.6.5  9nine9nine9nine  a1b2  aBcDeFg  AbCdEfG  [32ma.out[0m  a.Out  [34mA.out[0m  
a.zzzz  ___b  bees  c  ^^car  ^~car  [34mdir[0m  donkey  don.key  don..key  extra  
ex.txt  [34mfolder[0m  ^ghost  ^^ghost  ^~ghost  [34mgo88away68[0m  [34mgo89away67[0m  [34m.goaway[0m  
jhkhkj38278  l.cpp  [34m.look...at...that[0m  .ls.cpp  ls.cpp  lss.app  [34mlss.cp[0m  
lss.cpp  lSs.cpp  lSS.cpp  LsS.cpp  LSs.cpp  lss.pcc  ls.txt  [34mon1o[0m  .on2e  
on3e  one  one1  one2  out.a  ^pops  ~pops  ^popssss  race  ^race  ^^race  
^~race  ~^race  .race  r~ace  ra^ce  ra~ce  race^  racff  raf  ^raise  
^^raise  ~raise  .raise^the~~woof  raise^the~~woof  rEadme  README  REDfm  
res  Res  RES  resume  RESUME  *r*raise  this.9.is.8.a.7.file  this.is.a.file  
[34mthree[0m  two  z.aaaa  ~zz  

/home/alexander/Documents/test/*_*:
[34m.[0m  [34m..[0m  t-t  [34mT_T[0m  

/home/alexander/Documents/test/*_*/T_T:
[34m.[0m  [34m..[0m  .goaway  

/home/alexander/Documents/test/.8974:
[34m.[0m  [34m..[0m  

/home/alexander/Documents/test/A.out:
[34m^~^~^*@[0m  [34m.[0m  [34m..[0m  [34mB.out[0m  junk  thejunk  Thejunk  [34m~^Thejunk~Thejunk[0m  

/home/alexander/Documents/test/A.out/^~^~^*@:
[34m.[0m  [34m..[0m  [34m:B[0m  :D  T_T  

/home/alexander/Documents/test/A.out/^~^~^*@/:B:
[34m.[0m  [34m..[0m  [34mrotten[0m  YOOOO  

/home/alexander/Documents/test/A.out/^~^~^*@/:B/rotten:
[34m.[0m  [34m..[0m  [34mtomatoes[0m  

/home/alexander/Documents/test/A.out/^~^~^*@/:B/rotten/tomatoes:
[34m.[0m  [34m..[0m  

/home/alexander/Documents/test/A.out/B.out:
[34m.[0m  [34m..[0m  

/home/alexander/Documents/test/A.out/~^Thejunk~Thejunk:
[34m.[0m  [34m..[0m  

/home/alexander/Documents/test/dir:
[34m.[0m  [34m..[0m  [34msubdir[0m  

/home/alexander/Documents/test/dir/subdir:
[34m.[0m  [34m..[0m  [34msubsubdir[0m  

/home/alexander/Documents/test/dir/subdir/subsubdir:
[34m.[0m  [34m..[0m  [34msubsubsubdir[0m  

/home/alexander/Documents/test/dir/subdir/subsubdir/subsubsubdir:
[34m.[0m  [34m..[0m  notadir  

/home/alexander/Documents/test/folder:
[34m.[0m  [34m..[0m  

/home/alexander/Documents/test/go88away68:
[34m.[0m  [34m..[0m  

/home/alexander/Documents/test/go89away67:
[34m.[0m  [34m..[0m  

/home/alexander/Documents/test/.goaway:
[34m.[0m  [34m..[0m  

/home/alexander/Documents/test/.look...at...that:
[34m.[0m  [34m..[0m  

/home/alexander/Documents/test/lss.cp:
[34m.[0m  [34m..[0m  

/home/alexander/Documents/test/on1o:
[34m.[0m  [34m..[0m  

/home/alexander/Documents/test/three:
[34m.[0m  [34m..[0m  file.txt  justafile  
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls -Ra /home/alexander/Documents/test / A . o u t 
/home/alexander/Documents/test/A.out:
[34m^~^~^*@[0m  [34m.[0m  [34m..[0m  [34mB.out[0m  junk  thejunk  Thejunk  [34m~^Thejunk~Thejunk[0m  

/home/alexander/Documents/test/A.out/^~^~^*@:
[34m.[0m  [34m..[0m  [34m:B[0m  :D  T_T  

/home/alexander/Documents/test/A.out/^~^~^*@/:B:
[34m.[0m  [34m..[0m  [34mrotten[0m  YOOOO  

/home/alexander/Documents/test/A.out/^~^~^*@/:B/rotten:
[34m.[0m  [34m..[0m  [34mtomatoes[0m  

/home/alexander/Documents/test/A.out/^~^~^*@/:B/rotten/tomatoes:
[34m.[0m  [34m..[0m  

/home/alexander/Documents/test/A.out/B.out:
[34m.[0m  [34m..[0m  

/home/alexander/Documents/test/A.out/~^Thejunk~Thejunk:
[34m.[0m  [34m..[0m  
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls -Ra /home/alexander/Documents/test/A.out [K[K[K[K[K[K[C[1P /home/alexander/Documents/test/[1P /home/alexander/Documents/test/[1P /home/alexander/Documents/test/[1P/home/alexander/Documents/test/[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cls.cpp
/home/alexander/Documents/test/ls.cpp 
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls /home/alexander/Documents/test/ls.cpp[K[K[K[K[K[Ka.out
[32m/home/alexander/Documents/test/a.out[0m 
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls /home/alexander/Documents/test/a.out -l
-rwxrwxr-x 1 alexander alexander 49630 Oct 28 8:02 [32m/home/alexander/Documents/test/a.out
[0m]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ #testing d[Kfla[K[K[Kflags coming before p[Koptional parameters
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/l[Kls -a ./src
[34m.[0m  [34m..[0m  hw0.cpp  ls.cpp  
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls -a ./srcl./src[1P./src0./srcl./src[1P./src[1P./src-./srcl./src ./src
total 40
drwxrwxr-x 2 alexander alexander 4096 Nov 9 17:15 [34m.[0m
drwxrwxr-x 6 alexander alexander 4096 Nov 9 17:14 [34m..[0m
-rw-rw-r-- 1 alexander alexander 12361 Nov 9 13:11 hw0.cpp
-rw-rw-r-- 1 alexander alexander 16285 Nov 9 17:13 ls.cpp
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ bin/ls -a -l ./src[1P./src[1P./src[1P./src[1P./src ./src[C[C[C[C[C -l
total 40
drwxrwxr-x 2 alexander alexander 4096 Nov 9 17:15 [34m.[0m
drwxrwxr-x 6 alexander alexander 4096 Nov 9 17:14 [34m..[0m
-rw-rw-r-- 1 alexander alexander 12361 Nov 9 13:11 hw0.cpp
-rw-rw-r-- 1 alexander alexander 16285 Nov 9 17:13 ls.cpp
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ #ti[Khis concludes testing for now
]0;alexander@Lahela: ~/cs100/rshellalexander@Lahela:~/cs100/rshell$ exit
exit

Script done on Sun 09 Nov 2014 05:36:40 PM PST
