Script started on Tue 18 Nov 2014 10:55:56 PM PST
~
aorti017@hammer $ cs`0[K[K100
[0;91m
===============================================================================
|                                                                             |
| You have enabled settings specific for cs100.                               |
|                                                                             |
===============================================================================
[0m
[s%%%%%%%%%%[u[0;32maorti017[0;36m@[0;32mcs100[0;36m:[0;32m~[0;95m [0;36m$[0m cd rshell
[s%%%%%%%%%%[u[0;32maorti017[0;36m@[0;32mcs100[0;36m:[0;32m~/rshell[0;95m (redirect) [0;36m$[0m bin/rshell
aorti017@hammer.cs.ucr.edu$ #testing intput and output redirection
aorti017@hammer.cs.ucr.edu$ #when oup tu put file does not exit st
aorti017@hammer.cs.ucr.edu$ ls
bin  LICENSE  Makefile	README.md  src	tests
aorti017@hammer.cs.ucr.edu$ cat   ls>file
aorti017@hammer.cs.ucr.edu$ cat < file
bin
file
LICENSE
Makefile
README.md
src
tests
aorti017@hammer.cs.ucr.edu$ ls >> file 2   2 2 e2
aorti017@hammer.cs.ucr.edu$ cat <file2
bin
file
file2
LICENSE
Makefile
README.md
src
tests
aorti017@hammer.cs.ucr.edu$ #when output file ecist    xists
aorti017@hammer.cs.ucr.edu$ ls>  -a > file
aorti017@hammer.cs.ucr.edu$ cat < < file
.
..
bin
file
file2
.git
LICENSE
Makefile
README.md
src
tests
aorti017@hammer.cs.ucr.edu$ ls -a>>d file2
aorti017@hammer.cs.ucr.edu$ cat<file2
bin
file
file2
LICENSE
Makefile
README.md
src
tests
.
..
bin
file
file2
.git
LICENSE
Makefile
README.md
src
tests
aorti017@hammer.cs.ucr.edu$ #mixed
aorti017@hammer.cs.ucr.edu$ cat<file2>file
aorti017@hammer.cs.ucr.edu$ cat<file
bin
file
file2
LICENSE
Makefile
README.md
src
tests
.
..
bin
file
file2
.git
LICENSE
Makefile
README.md
src
tests
aorti017@hammer.cs.ucr.edu$ cat<file2>>file
aorti017@hammer.cs.ucr.edu$ cat<fie le
bin
file
file2
LICENSE
Makefile
README.md
src
tests
.
..
bin
file
file2
.git
LICENSE
Makefile
README.md
src
tests
bin
file
file2
LICENSE
Makefile
README.md
src
tests
.
..
bin
file
file2
.git
LICENSE
Makefile
README.md
src
tests
aorti017@hammer.cs.ucr.edu$ #testing piping
aorti017@hammer.cs.ucr.edu$ ls | grep bin
bin
aorti017@hammer.cs.ucr.edu$ ls|grep E|grep R
README.md
aorti017@hammer.cs.ucr.edu$ ls |grepe|^[[D       e|g  grep i| grep f
file
file2
Makefile
aorti017@hammer.cs.ucr.edu$ ls |grep notafileordir
aorti017@hammer.cs.ucr.edu$ #testing pipint wi    g with mixed IO   /O redirection
aorti017@hammer.cs.ucr.edu$ cat<Makefile|grep all
all:
	g++ -Wall -Werror -pedantic -ansi src/hw0.cpp -o bin/rshell
	g++ -Wall -Werror -ansi -pedantic src/cp.cpp -o bin/cp
	g++ -Wall -Werror -ansi -pedantic -std=c++0x src/ls.cpp -o bin/ls
	g++ -Wall -Werror -ansi -pedantic src/hw0.cpp -o bin/rshell
	g++ -Wall -Werror -ansi -pedantic src/cp.cpp -o bin/cp
	g++ -Wall -Werror -ansi -pedantic -std=c++11 src/ls.cpp -o bin/ls
aorti017@hammer.cs.ucr.edu$ cat<Makefile|cat<README.md|cat<LICENSE
Copyright (c) 2014, Alexander Ortiz
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following
conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following
disclaimer in the documentation and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote
products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
aorti017@hammer.cs.ucr.edu$ cat<README.md|CAT<    cat<MA akefile|cat< LICENSE| grep binary | grep above
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following
aorti017@hammer.cs.ucr.edu$ cat<Makefl ile| cat <README.md|                   grep bin|  cat< README.md| grep cp | cat<LICENSE | grep above | ls  | grep src
src
aorti017@hammer.cs.ucr.edu$ ps > file | grep rshell
aorti017@hammer.cs.ucr.edu$ ls>file | grep src
aorti017@hammer.cs.ucr.edu$ ls > file | grep bin | ls  ps > file | greo bin     p a.out
aorti017@hammer.cs.ucr.edu$ ls>file| cat<file>newfile | cat < newfile
bin
file
file2
LICENSE
Makefile
README.md
src
tests
aorti017@hammer.cs.ucr.edu$ ls -a  >newfile     ile |cat < newfile | ps > file
aorti017@hammer.cs.ucr.edu$ ;s  ls | cat<file>newfile |         >newfile| grep bin |p s   s ps| grep rshell | cat<file|read    README.md |grep cp | grep flag
execvp: Permission denied
aorti017@hammer.cs.ucr.edu$ #above command containt s typo
aorti017@hammer.cs.ucr.edu$ ls | catt <file>>newfile| grep bin |ps| grep rshell | cat<file|R cat<README.md |grep cp | grep flag
* ```cp``` can be used with the ```-a``` flag, which will copy using all methods. If no flag is specified it will be copied
aorti017@hammer.cs.ucr.edu$ echo ThiS  Is IS s a TeSt FiLe > test
aorti017@hammer.cs.ucr.edu$ cat < f test | tr A-Z az -z | tee out   newOutputfil   File1 | tr a-z A-Z > newOutputFile2
aorti017@hammer.cs.ucr.edu$ ct at < test
ThIs Is a TeSt FiLe
aorti017@hammer.cs.ucr.edu$ cat < newOutputFile2 1
this is a test file
aorti017@hammer.cs.ucr.edu$ cat < newou  OutputFile2
THIS IS A TEST FILE
aorti017@hammer.cs.ucr.edu$ cat<ls  file|ls>file|cat<MA akefile|ps>     | ps > curr_progrs    s | ca  ls | ls -a > hidd    aa llfile | grep g++
aorti017@hammer.cs.ucr.edu$ #testing custom i file descriptors
aorti017@hammer.cs.ucr.edu$ ls 0> temp
allfile  bin  curr_progs  file	file2  LICENSE	Makefile  newfile  newOutputFile1  newOutputFile2  README.md  src  temp  test  tests
aorti017@hammer.cs.ucr.edu$ cat < temp
aorti017@hammer.cs.ucr.edu$ ls 1> temp
aorti017@hammer.cs.ucr.edu$ cat < temp
allfile
bin
curr_progs
file
file2
LICENSE
Makefile
newfile
newOutputFile1
newOutputFile2
README.md
src
temp
test
tests
aorti017@hammer.cs.ucr.edu$ ls 2> temp
allfile  bin  curr_progs  file	file2  LICENSE	Makefile  newfile  newOutputFile1  newOutputFile2  README.md  src  temp  test  tests
aorti017@hammer.cs.ucr.edu$ cat < temp
aorti017@hammer.cs.ucr.edu$ ls nto  otafileordir 2> temp
aorti017@hammer.cs.ucr.edu$ cat < temp
ls: cannot access notafileordir: No such file or directory
aorti017@hammer.cs.ucr.edu$ ls 0>> file    temp
allfile  bin  curr_progs  file	file2  LICENSE	Makefile  newfile  newOutputFile1  newOutputFile2  README.md  src  temp  test  tests
aorti017@hammer.cs.ucr.edu$ cat <<  temp
ls: cannot access notafileordir: No such file or directory
aorti017@hammer.cs.ucr.edu$ ls 1>> temp
aorti017@hammer.cs.ucr.edu$ cat < f temp
ls: cannot access notafileordir: No such file or directory
allfile
bin
curr_progs
file
file2
LICENSE
Makefile
newfile
newOutputFile1
newOutputFile2
README.md
src
temp
test
tests
aorti017@hammer.cs.ucr.edu$ ls 2> temp c 
allfile  bin  curr_progs  file	file2  LICENSE	Makefile  newfile  newOutputFile1  newOutputFile2  README.md  src  temp  test  tests
aorti017@hammer.cs.ucr.edu$ cat     #abv ove command contains typo
aorti017@hammer.cs.ucr.edu$ #repeating pass t commn ands to restor file contents
aorti017@hammer.cs.ucr.edu$ ls 0>> temp
allfile  bin  curr_progs  file	file2  LICENSE	Makefile  newfile  newOutputFile1  newOutputFile2  README.md  src  temp  test  tests
aorti017@hammer.cs.ucr.edu$ ls 1>> temp
aorti017@hammer.cs.ucr.edu$ ls 2>> temp
allfile  bin  curr_progs  file	file2  LICENSE	Makefile  newfile  newOutputFile1  newOutputFile2  README.md  src  temp  test  tests
aorti017@hammer.cs.ucr.edu$ cat < temp
allfile
bin
curr_progs
file
file2
LICENSE
Makefile
newfile
newOutputFile1
newOutputFile2
README.md
src
temp
test
tests
aorti017@hammer.cs.ucr.edu$ ls notafileordir 2>> f temp
aorti017@hammer.cs.ucr.edu$ cat < temp
allfile
bin
curr_progs
file
file2
LICENSE
Makefile
newfile
newOutputFile1
newOutputFile2
README.md
src
temp
test
tests
ls: cannot access notafileordir: No such file or directory
aorti017@hammer.cs.ucr.edu$ #testing string input redirection 
aorti017@hammer.cs.ucr.edu$ cat <<< "this is a string!"
this is a string! aorti017@hammer.cs.ucr.edu$ wc <<< "this is also a string!"
      0       5      23
aorti017@hammer.cs.ucr.edu$ #this conl cludes testing
aorti017@hammer.cs.ucr.edu$ exit
[s%%%%%%%%%%[u[0;32maorti017[0;36m@[0;32mcs100[0;36m:[0;32m~/rshell[0;95m (redirect) [0;36m$[0m exit
exit
~
aorti017@hammer $ exit
exit

Script done on Tue 18 Nov 2014 11:14:34 PM PST
